INSTRUCTION_ERROR_RESERVE_FILE= 0
INSTRUCTION_WRONG_FILE_TYPE = 1
INSTRUCTION_SUCCESSFULLY_OPENED_FILE = 2
INSTRUCTION_RECORD_STARTED = 3
INSTRUCTION_RECORD_ESCAPED = 4

SCRIPT_TYPE_MOUSE_CLICK = 0
SCRIPT_TYPE_OTHER = 1
